name: Veracode Build Java Maven Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
  
#     runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          6.0.x
        source-url: ${{ env.MYGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.MYGET_TOKEN }}
    - name: Build
      run: |
        dotnet restore --configfile NuGet.Config
        dotnet publish -p:UseAppHost=False -p:MapFileExtensions=False -c Debug -o ./output --no-restore
    - name: Create zip archive
      run: zip -r veracode.zip ./output

#     - name: Setup .NET
#       run: |
#         choco install dotnetcore-sdk -y
#         dotnet --version
#     - name: Build application
#       run: |
#         dotnet restore
#         dotnet publish -c Debug -o ./output
        
#     - name: Setup 7zip
#       run: |
#         choco install 7zip -y
        
#     - name: Create zip archive
#       run: 7z a -tzip veracode.zip ./output
        
    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: veracode.zip
